# Generated by Django 4.1 on 2022-10-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GinRaiD_Reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='target',
        ),
    ]
