# Generated by Django 4.1 on 2022-10-10 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GinRaiD_Notifications', '0001_initial'),
        ('GinRaiD_Recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Information', to='GinRaiD_Recipes.menu'),
        ),
    ]
