# Generated by Django 4.1 on 2022-10-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GinRaiD_Recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
