# Generated by Django 4.1 on 2022-10-11 06:27

import GinRaiD_Recipes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GinRaiD_Recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='fav_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='GinRaiD_Recipes.menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Foodpic',
            field=models.ImageField(null=True, upload_to=GinRaiD_Recipes.models.image_file_path),
        ),
    ]
